{
 "title": "Container metrics by service",
 "tags": [
  "docker",
  "by service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(container_label_com_docker_swarm_task_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running replicas",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container_label_com_docker_swarm_task_name=~\"[[service]].+\"} > 0) by (container_label_com_docker_stack_namespace)"
    }
   ]
  },
  {
   "title": "Service totalt memory limit",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_label_com_docker_swarm_task_name=~\"[[service]].+\"})"
    }
   ]
  },
  {
   "title": "Total CPU limit for service",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{container_label_com_docker_swarm_task_name=~\"[[service]].+\"} / 100000)"
    }
   ]
  },
  {
   "title": "Memory usage as percent of limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of limit" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_task_name=~\"[[service]].+\"} / container_spec_memory_limit_bytes{container_label_com_docker_swarm_task_name=~\"[[service]].+\"}",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_cfs_throttled_seconds_total{container_label_com_docker_swarm_service_name=~\"$service\"}[5m])",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"$service\"}[1m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  }
 ]
}