{
 "title": "Pipeline metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network errors and packet drops per service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{container_label_com_docker_swarm_service_name!=\"\"}[5m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "Rcv errors: {{container_label_com_docker_swarm_service_name}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{container_label_com_docker_swarm_service_name!=\"\"}[5m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "Send errors: {{container_label_com_docker_swarm_service_name}}"
      },
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{container_label_com_docker_swarm_service_name!=\"\"}[5m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "Rcv drops: {{container_label_com_docker_swarm_service_name}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{container_label_com_docker_swarm_service_name!=\"\"}[5m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "Send drops: {{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "CPU throttling per service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "vCPUs" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{container_label_com_docker_swarm_service_name!=\"\"}[1m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "Memory saturation per service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit", "label": "Memory saturation percentage" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container_label_com_docker_swarm_service_name!=\"\"}) by (container_label_com_docker_swarm_service_name) / sum(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name!=\"\"}) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "CPU usage per service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "vCPUs" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!=\"\"}[1m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of vCPUs",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode))"
      }
     ]
    },
    {
     "title": "Total container CPU limit",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(container_spec_cpu_quota/100000)"
      }
     ]
    },
    {
     "title": "Total memory",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 2 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes)"
      }
     ]
    },
    {
     "title": "Total container memory limit",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 2 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{id=~\"/docker.*\"})"
      }
     ]
    },
    {
     "title": "% CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "sum(node_load5) without (cpu, mode) / (count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode)) * on (instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) by (instance) * on (instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  { "title": "Traefik (entrypoint)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Open connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{entrypoint=\"websecure\"}) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "404 as % of total nr of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=\"404\",entrypoint=\"websecure\"}[10m])) by (entrypoint) / sum(rate(traefik_entrypoint_requests_total{entrypoint=\"websecure\"}[10m])) by (entrypoint)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "5XX as % of total nr of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"^5.+\",entrypoint=\"websecure\"}[10m])) by (entrypoint) / sum(rate(traefik_entrypoint_requests_total{entrypoint=\"websecure\"}[10m])) by (entrypoint)",
     "legendFormat": "{{backend}} : {{code}}"
    }
   ]
  },
  {
   "title": "Median response time (q=0.5)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{entrypoint=\"websecure\"}[10m])) by (le, entrypoint))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Percentile response time (q=0.9)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{entrypoint=\"websecure\"}[10m])) by (le, entrypoint))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Requests/second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=\"websecure\"}[10m])) by (entrypoint)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  { "title": "Traefik (service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Open connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "404 as % of total nr of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=\"404\"}[10m])) by (service) / sum(rate(traefik_service_requests_total[10m])) by (service)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "5XX as % of total nr of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=~\"^5.+\"}[10m])) by (service) / sum(rate(traefik_service_requests_total[10m])) by (service)",
     "legendFormat": "{{backend}} : {{code}}"
    }
   ]
  },
  {
   "title": "Median response time (q=0.5)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(traefik_service_request_duration_seconds_bucket[10m])) by (le, service))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Percentile response time (q=0.9)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(traefik_service_request_duration_seconds_bucket[10m])) by (le, service))",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}