{
 "title": "Team dashboard",
 "tags": [ "team" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "query": "label_values(container_label_se_kth_team)"
   },
   { "name": "service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  { "title": "Docker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Docker events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "changes(sum(label_replace(devents_container_action{se_kth_team=~\"$team\", action=~\"restart\"}, \"img\", \"$1\", \"image\", \"[^/]+/([^@]*)@.*\")) by (img)[1m:])",
     "legendFormat": "restart: {{img}}"
    },
    {
     "expr": "changes(sum(label_replace(devents_container_action{se_kth_team=~\"$team\", action=~\"oom\"}, \"img\", \"$1\", \"image\", \"[^/]+/([^@]*)@.*\")) by (img)[1m:])",
     "legendFormat": "oom: {{img}}"
    },
    {
     "expr": "changes(sum(label_replace(devents_container_action{se_kth_team=~\"$team\", action=~\"die\"}, \"img\", \"$1\", \"image\", \"[^/]+/([^@]*)@.*\")) by (img)[1m:])",
     "legendFormat": "die: {{img}}"
    },
    {
     "expr": "changes(sum(label_replace(devents_container_action{se_kth_team=~\"$team\", action=~\"create\"}, \"img\", \"$1\", \"image\", \"[^/]+/([^@]*)@.*\")) by (img)[1m:])",
     "legendFormat": "create: {{img}}"
    }
   ]
  },
  { "title": "Container metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Task memory usage as a percent of docker-stack.yml memory limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory usage percentage" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_se_kth_team=~\"$team\"}) by (container_label_com_docker_swarm_task_name) / sum(container_spec_memory_limit_bytes{container_label_se_kth_team=~\"$team\"}) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "Task CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_se_kth_team=~\"$team\"}[5m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "Task CPU throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{container_label_se_kth_team=~\"$team\"}[5m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "Task network errors and packet drops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Errors & drops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{container_label_se_kth_team=~\"$team\"}[5m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "Rcv errors: {{container_label_com_docker_swarm_task_name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{container_label_se_kth_team=~\"$team\"}[5m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "Send errors: {{container_label_com_docker_swarm_task_name}}"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{container_label_se_kth_team=~\"$team\"}[5m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "Rcv drops: {{container_label_com_docker_swarm_task_name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{container_label_se_kth_team=~\"$team\"}[5m])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "Send drops: {{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  { "title": "Traefik metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "404 as % of total nr of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=\"404\",service=~\"$service\"}[10m])) by (service) / sum(rate(traefik_service_requests_total{service=~\"$service\"}[10m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "5XX as % of total nr of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=~\"5.*\",service=~\"$service\"}[10m])) by (service, code) / ignoring(code) group_left sum(rate(traefik_service_requests_total{service=~\"$service\"}[10m])) by (service)",
     "legendFormat": "{{service}} : {{code}}"
    }
   ]
  },
  {
   "title": "Median and 90 percentile response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[10m])) by (le, service))",
     "legendFormat": "{{service}} - median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[10m])) by (le, service))",
     "legendFormat": "{{service}} - 90 percentile"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Requests/second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service\"}[10m])) by (service)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Number of opened connections last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_open_connections{service=~\"$service\"}[5m])) by (service)",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}